name: Deploy Kaboom.js Project to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  release:
    types: [published]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js environment (if you use any node modules for building)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies (if you use a package.json)
      - name: Install dependencies
        run: npm ci

      # Build the project if necessary (replace with your build command if needed)
      # If Kaboom.js project is static and doesn't require a build step, you can skip this step
      - name: Build project
        run: npm run build # Make sure you have a build script in your package.json

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Change this to your output directory

